# Generated by Django 4.0 on 2024-11-30 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folowers', to='auth.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='folowing', to='auth.user')),
            ],
        ),
    ]
